kind: Secret
ansible_user: ENC[AES256_GCM,data:B8f2IUHX,iv:SLXq54K3B5bUSfPFWxcXXRv0Gcri+l1scxHKx8/vZFY=,tag:il1gXAtIcLJrRj2iYrbU5w==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:FJeu2DzyrsIq,iv:YzL4XPuyCm80zlKG5FydsPDDR50KEJ9y00ViiSky0dc=,tag:ns/F7bEiXAHq7hH7lSb2vA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-27T13:46:13Z"
    mac: ENC[AES256_GCM,data:Ypj5eD+PEzSEbM0eRIXdvF+KRu63SYzXgpIDrmD1HXIxzeIwgvjxLTzilVqrYTnQv5URmrWZ37jNlZL2PEzc0mUJvDfrMImJtfRl9BrYC1vqQNzZ8SNxz0EaLVZdo7ic51WDNZbppMBFiT5faEjEScBe/qMdFltOH+eTmzT7wF8=,iv:qDl2+g/CBnYNekfNjsbeN1T703OW3WJ6L91QmbA148Q=,tag:P+n4G3GbjEHUmnAOVwHxeA==,type:str]
    pgp:
        - created_at: "2021-10-27T13:46:13Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA+hEmM3aTUaZARAAgjz83VQxVkYZDpOww2BCC5EbCBV7ka7H0JqPznRqNb/H
            gesm/TDNdbY4HoMAwde7nCNlCkJgU9t1EHQ1zg2CSw7ST6sCJh9tO29kRNeay+u0
            cgE4BXAhs+0voQiCY/9s7xd7RLI0+w4L9IkppvdliwylzEPb38iqqK0RJKxHpqO/
            aXL+H190PkGn4O3CHF0KATWP+R33XA5TyCokbawz2P9B6awEIbmtJSOn8TWwiLlq
            avFabt40YPhxJ84F4V0P14T2Co1VplFDJjhWt4adzGpNpoJ3E2D/scD81dc+Szj7
            uXrz2zb9qGvMceIS17odfL4zgQ2krnP3P14dNABoqeJWV0ShKhZIuviKanQQOkl3
            laD0oEGm3nni6Gdv/iU2ANhhmkzUh013gSjqBHPB5sITY388VWenV4/rKkQ8ZE8K
            +xhVqimaodGgDI9TXBduZrH0zlkKSEbPiD2zYPzM+8yTuLcPVQ1RtMvR3v1Zl7AF
            uy0uamUXaquZPMvRafz/9c1wE8wcY6cel2/AtBU7bzCZAnrWVjNXjucrv2fPL47a
            WJAn43QjasufH+00gEoqi1dFyJxSdxPCJG1BZq7Dr+k96UTUzK4341KUVh6wO8Nl
            IGdad3EL4/qfpaYE0XcbP04H2iJp9+DGnkDqN1yjN3mdTyf/lrODRNtN9nMZyEvU
            aAEJAhCL9BM7yN3gGwz+uPSx47QSC2TjOYacZ5oSyPtASg/QrndGpyvZMygvKaxy
            3MTvK22yLeTk65ctE412B4awBpAmRrScs5wqV3M1cIC1ALtvy/ZTv/L4o34LDwu1
            RtuZFBrvLbj+
            =FUyM
            -----END PGP MESSAGE-----
          fp: 45BE90F4DB62B75ED5FD9C4BD9EA7F6B0A101C44
    unencrypted_regex: ^(kind)$
    version: 3.7.1
